### ISSUE TITLE
Optimize the nested for-loop in method get_live_video_id()

### ISSUE THREAD

**Issue by YunzheZJU** [pusaitou/mikochiku_alarm#26]
Glad to hear on Twitter that this project is keeping maintained.

According to the issue filed in https://twitter.com/aoi_erimiya/status/1251722814685474817 by 衿宮 葵 Sama, the nested for-loop written in method get_live_video_id() located in mikochiku_alarm.py could be optimized to get a better code readability.

One of the possible ways to optimization is the usage of Regular Expression.

I'm not quite familiar with the syntax of Python today so I just propose a sample solution in JavaScript here.

```javascript
// In JavaScript, syntax DOESNOT work in Python
const html = '' // '<!doctype html><html ... </html>', the plain text got from the body of https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos
const result = /window\["ytInitialData"] = .*LIVE NOW.*?"videoId":"([^"]+)".*;/.exec(html)
const videoId = result?.[1] // The target id, 'GevqnA0mX9M', for example
```

Here `/window\["ytInitialData"] = .*LIVE NOW.*?"videoId":"([^"]+)".*;/` is the core RegEx I construct. It is execute on the plain text `html` and the first `videoId` following the string `LIVE NOW` will be extracted.

Then `result?.[1]` get the 1st capturing group, which is the `([^"]+)` part, in the RegEx, if it is executed successfully. Operator `?.` stands for 'Return result[1] if result exists, otherwise `undefined`', where there is no active live streaming. In my poor Python language, this is similar to `videoId = result[1] if result else videoId = null`

Sorry for keeping typing in English because of my limited Japanese writing ability. Hope this suggection can help with the further development of Mikochiku_alarm.

**Comment by taizan-hokuto** [comment]
When I started to implement codes for this issue (#28) , I noticed that the working pattern is:
```
/window\["ytInitialData"\] = .*LIVE_NOW.*?"videoId":"([^"]+)".*;/
                        ^          ^
```

Would it be  due to the difference in language specification between JS and python ?

**Comment by pusaitou** [comment]
私もこのプロジェクトに参加しつづけてくれてうれしく思います
正規表現を使った方法は非常にシンプルでいいですね！
正規表現はあまりにも長いと可読性が下がると聞きましたがこれはいいですね！

私も英語が拙いですがよろしくおねがいします！

**Comment by pusaitou** [comment]
taizanさんも正規表現のプルリクありがとうございます！確認させていただきます

**Comment by YunzheZJU** [comment]
I have updated the RegEx in #26 to make it work correctly. Sorry for the inconvenience.

**Comment by taizan-hokuto** [comment]
Thank you for your support!

Quoted from #28 
> It's possible to extract all the active live stream video ids with the usage of the following RegEx `LIVE NOW.*?"videoId":"([^\"]+)"`.
> 
> ```python
> # Id of ChilledCow' s channel, where multiple live streams are active
> search_ch_id = "UCSJ4gkVC6NrvII8umztf0Ow"
> 
> # Used to extract the value of window["ytInitialData"]
> PATTERN_DATA = re.compile(r'window\["ytInitialData"\] = (.*?);')
> 
> # Used to extract the FIRST value of `videoId` following `LIVE NOW`
> PATTERN_LIVE_VIDEO  = re.compile(r'LIVE_NOW.*?"videoId":"([^"]+)"')
> 
> html = session.get("https://www.youtube.com/channel/" + search_ch_id, headers=HEADERS, timeout=10)
> 
> # Value of 'ytInitialData', just for safety, in case where 'LIVE_NOW' exists somewhere out of ytInitialData
> data= re.search(PATTERN_DATA , html.text)
> 
> # Find first values of `videoId` following EVERY `LIVE NOW`
> video_ids = PATTERN_LIVE_VIDEO.findall(data)
> 
> for video_id in video_ids:
>     print videoId
>     // Processing...
> ```
> 
> You can even inline all of the above into just two lines...

I will try this code.

**Comment by pusaitou** [comment]
taizanさん動作確認感謝します！よければtaizanさんが前回プルリクいただいた分を訂正して再度プルリクを投げていただけないでしょうか？よろしくお願いします！
