### ISSUE TITLE
Query video id from a lighter API

### ISSUE THREAD

**Issue by YunzheZJU** [pusaitou/mikochiku_alarm#27]
Update:  2 New methods added as mentioned by answers on stackoverflow.
------------------------
Update: The 4th url, 'Query API used in mobile video page', has been updated to a much lighter one.
------------------------
A lighter API offers less network traffic usage and faster response.

Here I have compared the network traffic usages of some different ways to get the active live stream video ids.
* Home page of a channel `https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA` This usually takes around **61.5KB** (length of encoded content) per Response, under `content-encoding: br` and `http2`.
* Video page `https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos` **44.9KB**
* Mobile video page`https://m.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos`  **29.8KB**
* Query API used in mobile video page `https://m.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos?view=2&flow=list&pbj=1` **5.3KB** Currently I'm just sure that this request will do give me a light enough response but have no idea how to construct the header params. (I give up in the Chrome extension environment where User-Agent can not be modified. But Python env of mikochiku_alarm may make it!) **This api may give an incorrect result where a live is marked as not started until several minutes after the live has actually started.** More info: #76 
* Official API documented at `https://developers.google.com/youtube/v3/docs/videos/list` Untested. This should be the lightest API but requests at least a Google Developer `API key`, as mentioned in https://twitter.com/hidori_/status/1251877795367514113
* Embed player https://stackoverflow.com/a/46394890 Active videoId can be found ONLY WHEN there is an active livestreaming or a scheduled one. A dummy(fake) videoId can be found if the livestream is MEMBERS-ONLY.
* Route `/live` of a channel. Format `https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/live`. The video list page would be returned if there is no active or scheduled livestream, or the active videoId can be found in the source code.

**Comment by pusaitou** [comment]
検証ありがとうございます！https://m.youtube.com/channel/<ID>/videos?view=57&flow=list&pbj=1 が一番ベストということですかね？
私のローカル環境でも検証したいのでやり方を教えていただけますか？


私が試した方法はなにか間違ってそうで・・・
>>> import requests
>>> requests.get("https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA")
<Response [200]>
>>> a = requests.get("https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA")
>>> import sys
>>> sys.getsizeof(a)
56
>>> a = requests.get("https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA")
>>> sys.getsizeof(a)
56
>>> a = requests.get("https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos")
>>> sys.getsizeof(a)
56
>>> a = requests.get("https://m.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos")
>>> sys.getsizeof(a)
56
>>> a = requests.get("https://m.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos?view=57&flow=list&pbj=1")
>>> sys.getsizeof(a)
56
>>> a = requests.get("https://developers.google.com/youtube/v3/docs/videos/list")
>>> sys.getsizeof(a)
56
>>> a = requests.get("https://m.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA/videos?view=57&flow=list&pbj=1")
>>> a.text

**Comment by YunzheZJU** [comment]
It may be a bit difficult to get the size of a raw response returned from python-request. And sys.getsizeof does not help anything here according to https://stackoverflow.com/a/50825553. 

Are you familiar with the usage of Chrome DevTools?

1. Open a new tab in Chrome, then open the DevTools with `F12`. Switch to the `Network` panel and toggle on `Perserve log` and `Disable cache`, then activate the 'Doc' filter ('All' is the default).
1. Be aware that you must toggle on the 'Toggle Device Toobar' before you access any url prefixed with 'm.youtube.com'. Chrome will automatically switch to the proper User-Agent under this 'mobile mode'.
![2020-04-20 15 10 47 copy](https://user-images.githubusercontent.com/23452609/79726143-e9058f00-831c-11ea-8d6c-aa27aae2d39d.png)
1. Access the urls one by one and you can view the differences between the requests, e.g. Size!
1. Construct the python request params to simulate the requests. Do not forget to add the proper User-Agent.

`https://m.youtube.com/channel/UCSJ4gkVC6NrvII8umztf0Ow/videos?view=2&flow=list&pbj=1` This request will be fired by following this procedure: 
1. Access `https://m.youtube.com/channel/UCSJ4gkVC6NrvII8umztf0Ow/videos` with 'Toggle Device Toobar' on and switch the filter from 'Doc' to 'XHR'.
1. Switch the filter 'Uploads' in the webpage to 'Live streams'
![2020-04-20 15 25 29](https://user-images.githubusercontent.com/23452609/79725744-3cc3a880-831c-11ea-9935-32dd36445f60.png)
1. A request to `https://m.youtube.com/channel/UCSJ4gkVC6NrvII8umztf0Ow/videos` with query string `?view=2&flow=list&pbj=1` is fired. The response contains a list of live stream infos and is exactly what we want.
![2020-04-20 15 34 04](https://user-images.githubusercontent.com/23452609/79725827-62e94880-831c-11ea-9ea1-7e78a4163db7.png)

**Comment by pusaitou** [comment]
stackoverflowでも見たことがないくらい丁寧な解説をありがとうございます！お手数をおかけしました。試させていただきます！

**Comment by YunzheZJU** [comment]
Merged
