### ISSUE TITLE
YouTube利用規約に関して

### ISSUE THREAD

**Issue by Sayamame-beans** [pusaitou/mikochiku_alarm#33]
# 注意
以下の文章はあくまでも"さやまめ"による個人的な解釈であり、その全てにおいて正当なものであることを保証しません。ご了承下さい。<br>

Twitterで利用規約の解釈についてのツイートをしましたが、その後新たな問題点を発見したため、その問題点と、今回関係のある他の部分について、纏めと共有をさせて頂きます。

## YouTube利用規約について
YouTube利用規約 : https://www.youtube.com/static?template=terms&hl=ja&gl=JP <br>
利用規約内の"許可と制限事項"を参照すると、

> お客様は、本契約および適用される法律を遵守する限り、本サービスにアクセスして利用できます。お客様は個人的で、非営利目的の用途でコンテンツを視聴できます。また、埋め込み型 YouTube プレーヤーに YouTube 動画を表示させることもできます。<br>
> 本サービスの利用には制限があり、以下の行為が禁止されています。<br>

とあり、この内の3番が抵触する可能性のある箇所で、

> 自動化された手段（ロボット、ボットネット、スクレーパなど）を使用して本サービスにアクセスすること。ただし、（a）公開されている検索エンジンを YouTube の robots.txt ファイルに従って使用する場合、または（b）YouTube が事前に書面で許可している場合を除きます。<br>

となっています。
ここに問題がありまして、この日本語版の利用規約では**公開されている検索エンジン**でなければ、例え**robots.txtに従っていたとしても**、アクセスしてはならない事になってしまいます。
しかし、英語版の利用規約を確認すると、以下のようになります。
Terms of Service : https://www.youtube.com/static?template=terms&hl=en&gl=US <br>
>You are not allowed to:
>\~中略\~
>3. access the Service using any automated means (such as robots, botnets or scrapers) except (a) in the case of public search engines, in accordance with YouTube’s robots.txt file; or (b) with YouTube’s prior written permission; <br>

この文章は、「公開された検索エンジンを使用する場合や、YouTube の robots.txtに従っている場合、又はYouTubeが事前に書面で許可した場合を除き、自動化された手段でサービスにアクセスする事は禁止されています」と解釈出来ると思うんです。
```
(a)と(b)では()と ; で明示的に区別されているので、except in と except withで分かれていると考えられる。では(a)内部のin2つはどうか？
, で区切られていることから、後ろのin accordance withは public search enginesに掛からないと考えられる。
とすればこの部分は、except in the case of public search enginesとexcept in accordance with YouTube’s robots.txt fileの2つに分かれると考えられる。
```
**この英文の解釈は信頼性が十分でないため、後日知人に確認します。**

更に、**既存の検索エンジンの構成を変更して、robots.txtに従わないようにする**ということは出来ないはずなので、そもそも公開された検索エンジンをrobots.txtに従わないように使用する、という事は出来ないはずです。
とすれば、あるとしても"robots.txtに従わない、公開された検索エンジン"ですが、その場合は、**robots.txtに従っている、公開された検索エンジンを使用する場合**と記述するはずで、言葉の順序が逆になります。

以上のことから、実際に規約がどういった意味であるのかは公式に確認を取る必要があるかもしれません。
この部分の英語版の解釈や、日本語版の表現の違和感について、こちらの方で議論して頂けると助かります...

次に、この部分が問題なく、robots.txtに従ってアクセスすればよい場合について記述します。
## YouTube の robots.txtとは？
robots.txt : https://www.youtube.com/robots.txt
Googleでのrobots.txtの処理方法(参考) : https://developers.google.com/search/reference/robots_txt?hl=ja

これを参照すると、みこ畜アラームでアクセスしている(アクセス予定の)
+ ~.com/user/<ID>
+ ~.com/channel/<ID>
+ ~.com/watch?v=<ID>
は、アクセスしても問題のない箇所だと思われます。
ですので、過剰に繰り返しアクセスしたり(DoS攻撃に近い)、利用規約内、許可と制限事項の6番に違反しない限りは問題が無いと思われます。
> ### 利用規約 許可と制限事項 6番
> 本来のユーザー エンゲージメントの測定結果を歪めること、またはそのように仕向けること。たとえば、ユーザーに金銭を支払ったりインセンティブを与えたりして、動画の視聴回数、高評価数、低評価数を増やす、チャンネル登録者を増やす、またはその他なんらかの方法で指標を操作することなどが含まれます。<br>

また、Googleでのrobots.txtの処理方法を参照すると、
> ### 適用性
> このドキュメントで規定されているガイドラインは、Google のすべての自動クローラに適用されます。ユーザーに代わってエージェントが URL にアクセスする場合（たとえば、翻訳、手動登録フィード、マルウェア解析を目的として）は、これらのガイドラインを適用する必要はありません。<br>

と書いてあるため、**ユーザーに代わってエージェントが URL にアクセスする**の範囲を逸脱しない限りは、私達もrobots.txtで禁止されている箇所にアクセスすることが認められる**かも**しれません。

以上が現段階での利用規約に関するまとめになります。
参考になると幸いです。

**Comment by hidori-11** [comment]
まとめ、大変助かります
ありがとうございます

やはり現状グレーゾーンっぽいですね・・・
留意しておきます

**Comment by pusaitou** [comment]
お忙しい中こんなにも丁寧にまとめてくださりありがとうございます！
完全に禁止だと思ってましたがしっかりと規約をみてみるとgoogleも有情なんだと思わせてくれますね
非常に目から鱗な情報でとても助かります！ありがとうございました！
規約の英語や日本語の解釈などさらに深めていきたいですね
