### ISSUE TITLE
.gitignoreはリポジトリーに追加するべきかどうか

### ISSUE THREAD

**Issue by pusaitou** [pusaitou/mikochiku_alarm#47]
これいつも迷うんです

**Comment by taizan-hokuto** [comment]
個人的な意見としては、.gitignoreをリポジトリに追加してもよいと思います。
メリット：
不要なファイルが不注意でリモートリポジトリにpushされてしまうのを防げる。

デメリット：
除外したいファイルはユーザーによって千差万別であり、フォーク元のgitignoreが肥大化する可能性がある（コンフリクトも起こる？未検証）

.gitignoreにどんなファイルを指定するべきかについて、下記のページで述べられていました。

https://blog.tai2.net/gitignore.html

厳格な流儀としては、
+ __pycache__フォルダ等、「pythonで開発するうえで発生するが除外すべきファイル」は、プロジェクトの.gitignoreに記述する。

+ ,DS_storeや*swpやThumbs.db等、「個人環境に依存して発生するファイル」は、
各自の~/.gitconfig（Windowsならば users\ユーザ名\ .gitconfig）ファイルのexcludesfile  項目に
グローバルで除外するファイルを指定するらしいです。
https://qiita.com/katsew/items/5cade12fa743a2f31f25

※私はこのやり方はとらず、除外したいファイルを全部ローカルリポジトリの.gitignoreに指定しています。
そして.gitignoreに.gitignore自身を指定してpushされないようにしています。

最初から.gitignoreを用意しておくと参加しようとするユーザーさんに親切かなとは思います
。
（その後いろいろなファイルが追加されたとしても目をつむる）

※リモート上の.gitignoreのファイル内容を固定することって可能なのでしょうか。
リモートリポジトリに用意した.gitignoreの内容は、各自がフォーク時にコピーされますが、
開発中に各ユーザーが.gitignoreを追加・変更した後フォーク元にpushしたとしてもフォーク元は無視できるような設定ってできるのでしょうか。

**Comment by YunzheZJU** [comment]
Despite the links provided by Taizan-hokuto Sama, here is a Third-party plugin for PyCharm (as well as for IntelliJ) named `.ignore`.

It can help developers to generate `.gitignore` file.

However it may contain a lot of unwanted rules.

![截屏2020-04-24 19 08 24](https://user-images.githubusercontent.com/23452609/80206643-4708de00-865f-11ea-9b89-1dddd2112b16.png)
![截屏2020-04-24 19 11 31](https://user-images.githubusercontent.com/23452609/80206707-6ef84180-865f-11ea-9558-5f80243c6d4d.png)

**Comment by pusaitou** [comment]
github公式からgitignoreのテンプレが公開されてるみたいです
https://github.com/github/gitignore/blob/master/Python.gitignore
YunzheZJUさんのやつと同じかな？
そうなると問題は.DS_Storeは含めるべきかということになりますがこれは好みになりますよね
開発者さんにより使ってもらえやすそうなので入れたいと思います！
他に除外したいものがあれば言ってください（.vscodeとか除外に欲しい人いますか？）
逆にdist/や.envなどは除外してはいけないので外しておきます
外しとかないといけないものなどあったら言ってください
私が.gitignoreを追加しておきますね

**Comment by YunzheZJU** [comment]
Oh...Yes! They are almost the same.
