### ISSUE TITLE
「JSONのパースに失敗しました」と表示され、動画情報が正常に取得できない。

### ISSUE THREAD

**Issue by taizan-hokuto** [pusaitou/mikochiku_alarm#48]
## 原因：

元凶は私のこのコミットです。→https://github.com/pusaitou/mikochiku_alarm/pull/38/commits/926ba7ad1a7500fe45bfa0eb1ee1e552e9a77259

pythonの環境に、brotliモジュールがインストールされていない場合、
取得した圧縮データが正常に展開されず、そのままJSONパースされ、
エラーになります。

requestsモジュール内部にbrotliが搭載されているから大丈夫という私の考察は誤りでした.

スクリプト中でbrotliをインポートしなくても、brotliがインストールされてさえいれば正常に展開できるのが盲点でした。

## 修正手順：
requirements.txtに下記を加えます。
```
brotli==1.0.7
```

開発中の方ですでに、https://github.com/pusaitou/mikochiku_alarm/commit/8b9e627a25571899ae0e4c51c29b839edcb83028
を取り込まれている場合は、ターミナルで
```
pip --install brotli
```
を実行するとBrotliをインストールできます。

**Comment by pusaitou** [comment]
なんというか盲点すぎるバグですね・・・
pythonファイルを起動するときにrequestsモジュールをインストールしてたがためにモジュールのbrotliがありませんと言われないのはバグの原因究明が非常に厄介になりそう

**Comment by taizan-hokuto** [comment]
迅速なマージありがとうございました。
