### ISSUE TITLE
タスクトレイに格納（Windows）

### ISSUE THREAD

**Issue by taizan-hokuto** [pusaitou/mikochiku_alarm#52]
タスクトレイ格納時に右クリックしたときのメニュー実装も同時に必要になりますかね

**Comment by pusaitou** [comment]
おお！本格的
タスクトレイ（標準ではwindowsのバーの右下らへんにあるアイコン軍みたいなやつ）に格納することの利点ってなんですか？

**Comment by taizan-hokuto** [comment]
ウィンドウやタスクバーに非表示の状態で常駐させることができるくらいですね。
最小化時は常にタスクトレイに入れるかどうか、オプションで選べるようにしてもいいかもしれません。

**Comment by pusaitou** [comment]
いいですね！アラームにぴったしの機能だと思います！
