### ISSUE TITLE
Remove duplicated files from version control

### ISSUE THREAD

**Issue by YunzheZJU** [pusaitou/mikochiku_alarm#73]
Contents in `dist/res/` seem to be a copy of `res/`. 
Maybe we can run a script before build to duplicate them, or make a symbol link, to reduce the repo's size.

**Comment by taizan-hokuto** [comment]
I deleted and added the resource files in `dist/res/` to .gitignore. 
The resource files in `res/` are copied to `dist/res/` when pyinstaller is executed.
